/*
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import it.unimi.xtext.ide.contentassist.antlr.internal.InternalKantParser;
import it.unimi.xtext.services.KantGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class KantParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(KantGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, KantGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getFunctionKeyAccess().getAlternatives(), "rule__FunctionKey__Alternatives");
			builder.put(grammarAccess.getFunctionReturnAccess().getAlternatives(), "rule__FunctionReturn__Alternatives");
			builder.put(grammarAccess.getPropertyDefAccess().getPropertyAlternatives_1_0(), "rule__PropertyDef__PropertyAlternatives_1_0");
			builder.put(grammarAccess.getKnowledgeAccess().getAlternatives(), "rule__Knowledge__Alternatives");
			builder.put(grammarAccess.getKnowledgeDefAccess().getAlternatives(), "rule__KnowledgeDef__Alternatives");
			builder.put(grammarAccess.getKnowledgeDefAccess().getAlternatives_0_0(), "rule__KnowledgeDef__Alternatives_0_0");
			builder.put(grammarAccess.getKnowledgeDefAccess().getAlternatives_1_0(), "rule__KnowledgeDef__Alternatives_1_0");
			builder.put(grammarAccess.getKnowledgeDefAccess().getAlternatives_1_1(), "rule__KnowledgeDef__Alternatives_1_1");
			builder.put(grammarAccess.getKnowledgeDefDestructuringAccess().getAlternatives(), "rule__KnowledgeDefDestructuring__Alternatives");
			builder.put(grammarAccess.getKnowledgeDefListDesctructuringAssignmentAccess().getAlternatives(), "rule__KnowledgeDefListDesctructuringAssignment__Alternatives");
			builder.put(grammarAccess.getKnowledgeValueAccess().getAlternatives(), "rule__KnowledgeValue__Alternatives");
			builder.put(grammarAccess.getKnowledgeListAccess().getValuesAlternatives_2_0_0(), "rule__KnowledgeList__ValuesAlternatives_2_0_0");
			builder.put(grammarAccess.getKnowledgeListAccess().getValuesAlternatives_2_1_1_0(), "rule__KnowledgeList__ValuesAlternatives_2_1_1_0");
			builder.put(grammarAccess.getKnowledgeSetAccess().getContentAlternatives_2_0_0(), "rule__KnowledgeSet__ContentAlternatives_2_0_0");
			builder.put(grammarAccess.getKnowledgeSetAccess().getContentAlternatives_2_1_1_0(), "rule__KnowledgeSet__ContentAlternatives_2_1_1_0");
			builder.put(grammarAccess.getKnowledgeSpreadingAccess().getRefAlternatives_1_0(), "rule__KnowledgeSpreading__RefAlternatives_1_0");
			builder.put(grammarAccess.getKnowledgeFromFunctionArgAccess().getAlternatives(), "rule__KnowledgeFromFunctionArg__Alternatives");
			builder.put(grammarAccess.getScenarioBranchingAccess().getAlternatives(), "rule__ScenarioBranching__Alternatives");
			builder.put(grammarAccess.getCheckAccess().getAlternatives_1(), "rule__Check__Alternatives_1");
			builder.put(grammarAccess.getUniversalIntroductionAccess().getGroup(), "rule__UniversalIntroduction__Group__0");
			builder.put(grammarAccess.getUniversalIntroductionAccess().getGroup_2(), "rule__UniversalIntroduction__Group_2__0");
			builder.put(grammarAccess.getFunctionDefAccess().getGroup(), "rule__FunctionDef__Group__0");
			builder.put(grammarAccess.getFunctionDefAccess().getGroup_3(), "rule__FunctionDef__Group_3__0");
			builder.put(grammarAccess.getFunctionDefAccess().getGroup_3_2(), "rule__FunctionDef__Group_3_2__0");
			builder.put(grammarAccess.getFunctionDefAccess().getGroup_4(), "rule__FunctionDef__Group_4__0");
			builder.put(grammarAccess.getFunctionDefAccess().getGroup_5(), "rule__FunctionDef__Group_5__0");
			builder.put(grammarAccess.getFunctionDefAccess().getGroup_7(), "rule__FunctionDef__Group_7__0");
			builder.put(grammarAccess.getFunctionParamAccess().getGroup(), "rule__FunctionParam__Group__0");
			builder.put(grammarAccess.getFunctionParamAccess().getGroup_3(), "rule__FunctionParam__Group_3__0");
			builder.put(grammarAccess.getFunctionKeyAccess().getGroup_1(), "rule__FunctionKey__Group_1__0");
			builder.put(grammarAccess.getFunctionKeyAccess().getGroup_1_2(), "rule__FunctionKey__Group_1_2__0");
			builder.put(grammarAccess.getFunctionKeyElementAccess().getGroup(), "rule__FunctionKeyElement__Group__0");
			builder.put(grammarAccess.getFunctionKeyElementAccess().getGroup_1(), "rule__FunctionKeyElement__Group_1__0");
			builder.put(grammarAccess.getFunctionReturnAccess().getGroup_1(), "rule__FunctionReturn__Group_1__0");
			builder.put(grammarAccess.getFunctionReturnAccess().getGroup_1_2(), "rule__FunctionReturn__Group_1_2__0");
			builder.put(grammarAccess.getFunctionReturnElementAccess().getGroup(), "rule__FunctionReturnElement__Group__0");
			builder.put(grammarAccess.getFunctionReturnElementAccess().getGroup_1(), "rule__FunctionReturnElement__Group_1__0");
			builder.put(grammarAccess.getPropertyDefAccess().getGroup(), "rule__PropertyDef__Group__0");
			builder.put(grammarAccess.getKnowledgeEqualityDefAccess().getGroup(), "rule__KnowledgeEqualityDef__Group__0");
			builder.put(grammarAccess.getFunctionInversionDefAccess().getGroup(), "rule__FunctionInversionDef__Group__0");
			builder.put(grammarAccess.getKnowledgeBaseAccess().getGroup(), "rule__KnowledgeBase__Group__0");
			builder.put(grammarAccess.getPrincipalAccess().getGroup(), "rule__Principal__Group__0");
			builder.put(grammarAccess.getPrincipalAccess().getGroup_2(), "rule__Principal__Group_2__0");
			builder.put(grammarAccess.getPrincipalAccess().getGroup_3(), "rule__Principal__Group_3__0");
			builder.put(grammarAccess.getKnowledgeDefAccess().getGroup_0(), "rule__KnowledgeDef__Group_0__0");
			builder.put(grammarAccess.getKnowledgeDefAccess().getGroup_1(), "rule__KnowledgeDef__Group_1__0");
			builder.put(grammarAccess.getKnowledgeDefAccess().getGroup_1_1_1(), "rule__KnowledgeDef__Group_1_1_1__0");
			builder.put(grammarAccess.getKnowledgeDefAccess().getGroup_1_1_1_2(), "rule__KnowledgeDef__Group_1_1_1_2__0");
			builder.put(grammarAccess.getKnowledgeDefSetDestructuringAccess().getGroup(), "rule__KnowledgeDefSetDestructuring__Group__0");
			builder.put(grammarAccess.getKnowledgeDefSetDestructuringAccess().getGroup_2(), "rule__KnowledgeDefSetDestructuring__Group_2__0");
			builder.put(grammarAccess.getKnowledgeDefSetDestructuringAccess().getGroup_2_1(), "rule__KnowledgeDefSetDestructuring__Group_2_1__0");
			builder.put(grammarAccess.getKnowledgeDefSetDesctructuringAssignmentAccess().getGroup(), "rule__KnowledgeDefSetDesctructuringAssignment__Group__0");
			builder.put(grammarAccess.getKnowledgeDefSetDesctructuringAssignmentAccess().getGroup_1(), "rule__KnowledgeDefSetDesctructuringAssignment__Group_1__0");
			builder.put(grammarAccess.getKnowledgeDefListDestructuringAccess().getGroup(), "rule__KnowledgeDefListDestructuring__Group__0");
			builder.put(grammarAccess.getKnowledgeDefListDestructuringAccess().getGroup_2(), "rule__KnowledgeDefListDestructuring__Group_2__0");
			builder.put(grammarAccess.getKnowledgeDefListDestructuringAccess().getGroup_2_1(), "rule__KnowledgeDefListDestructuring__Group_2_1__0");
			builder.put(grammarAccess.getKnowledgeDefListDesctructuringAssignmentAccess().getGroup_0(), "rule__KnowledgeDefListDesctructuringAssignment__Group_0__0");
			builder.put(grammarAccess.getKnowledgeDefListDesctructuringAssignmentAccess().getGroup_1(), "rule__KnowledgeDefListDesctructuringAssignment__Group_1__0");
			builder.put(grammarAccess.getKnowledgeListAccess().getGroup(), "rule__KnowledgeList__Group__0");
			builder.put(grammarAccess.getKnowledgeListAccess().getGroup_2(), "rule__KnowledgeList__Group_2__0");
			builder.put(grammarAccess.getKnowledgeListAccess().getGroup_2_1(), "rule__KnowledgeList__Group_2_1__0");
			builder.put(grammarAccess.getKnowledgeRefAccess().getGroup(), "rule__KnowledgeRef__Group__0");
			builder.put(grammarAccess.getKnowledgeRefAccess().getGroup_1(), "rule__KnowledgeRef__Group_1__0");
			builder.put(grammarAccess.getKnowledgeSetAccess().getGroup(), "rule__KnowledgeSet__Group__0");
			builder.put(grammarAccess.getKnowledgeSetAccess().getGroup_2(), "rule__KnowledgeSet__Group_2__0");
			builder.put(grammarAccess.getKnowledgeSetAccess().getGroup_2_1(), "rule__KnowledgeSet__Group_2_1__0");
			builder.put(grammarAccess.getKnowledgeSpreadingAccess().getGroup(), "rule__KnowledgeSpreading__Group__0");
			builder.put(grammarAccess.getKnowledgeGeneratorAccess().getGroup(), "rule__KnowledgeGenerator__Group__0");
			builder.put(grammarAccess.getKnowledgeFromFunctionAccess().getGroup(), "rule__KnowledgeFromFunction__Group__0");
			builder.put(grammarAccess.getKnowledgeFromFunctionAccess().getGroup_4(), "rule__KnowledgeFromFunction__Group_4__0");
			builder.put(grammarAccess.getKnowledgeFromFunctionArgAccess().getGroup_0(), "rule__KnowledgeFromFunctionArg__Group_0__0");
			builder.put(grammarAccess.getKnowledgeFromFunctionArgAccess().getGroup_0_1(), "rule__KnowledgeFromFunctionArg__Group_0_1__0");
			builder.put(grammarAccess.getCommunicationAccess().getGroup(), "rule__Communication__Group__0");
			builder.put(grammarAccess.getCommunicationAccess().getGroup_1(), "rule__Communication__Group_1__0");
			builder.put(grammarAccess.getCommunicationAccess().getGroup_4(), "rule__Communication__Group_4__0");
			builder.put(grammarAccess.getScenarioOptionalAccess().getGroup(), "rule__ScenarioOptional__Group__0");
			builder.put(grammarAccess.getScenarioAlternativesAccess().getGroup(), "rule__ScenarioAlternatives__Group__0");
			builder.put(grammarAccess.getScenarioAlternativesAccess().getGroup_1(), "rule__ScenarioAlternatives__Group_1__0");
			builder.put(grammarAccess.getScenarioAlternativesAccess().getGroup_2(), "rule__ScenarioAlternatives__Group_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup(), "rule__Scenario__Group__0");
			builder.put(grammarAccess.getCheckAccess().getGroup(), "rule__Check__Group__0");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getGroup(), "rule__KnowledgeCheck__Group__0");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getGroup_2(), "rule__KnowledgeCheck__Group_2__0");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getGroup_2_1(), "rule__KnowledgeCheck__Group_2_1__0");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getGroup_3(), "rule__KnowledgeCheck__Group_3__0");
			builder.put(grammarAccess.getEqualityCheckAccess().getGroup(), "rule__EqualityCheck__Group__0");
			builder.put(grammarAccess.getEqualityCheckAccess().getGroup_1(), "rule__EqualityCheck__Group_1__0");
			builder.put(grammarAccess.getFreshnessCheckAccess().getGroup(), "rule__FreshnessCheck__Group__0");
			builder.put(grammarAccess.getFreshnessCheckAccess().getGroup_1(), "rule__FreshnessCheck__Group_1__0");
			builder.put(grammarAccess.getLinkabilityCheckAccess().getGroup(), "rule__LinkabilityCheck__Group__0");
			builder.put(grammarAccess.getLinkabilityCheckAccess().getGroup_1(), "rule__LinkabilityCheck__Group_1__0");
			builder.put(grammarAccess.getAuthenticationCheckAccess().getGroup(), "rule__AuthenticationCheck__Group__0");
			builder.put(grammarAccess.getProtocolAccess().getElementsAssignment(), "rule__Protocol__ElementsAssignment");
			builder.put(grammarAccess.getUniversalIntroductionAccess().getArgsAssignment_1(), "rule__UniversalIntroduction__ArgsAssignment_1");
			builder.put(grammarAccess.getUniversalIntroductionAccess().getArgsAssignment_2_1(), "rule__UniversalIntroduction__ArgsAssignment_2_1");
			builder.put(grammarAccess.getFunctionDefAccess().getIntroAssignment_1(), "rule__FunctionDef__IntroAssignment_1");
			builder.put(grammarAccess.getFunctionDefAccess().getNameAssignment_2(), "rule__FunctionDef__NameAssignment_2");
			builder.put(grammarAccess.getFunctionDefAccess().getParamsAssignment_3_1(), "rule__FunctionDef__ParamsAssignment_3_1");
			builder.put(grammarAccess.getFunctionDefAccess().getParamsAssignment_3_2_1(), "rule__FunctionDef__ParamsAssignment_3_2_1");
			builder.put(grammarAccess.getFunctionDefAccess().getKeyAssignment_4_1(), "rule__FunctionDef__KeyAssignment_4_1");
			builder.put(grammarAccess.getFunctionDefAccess().getReturnAssignment_5_1(), "rule__FunctionDef__ReturnAssignment_5_1");
			builder.put(grammarAccess.getFunctionDefAccess().getRandomizedAssignment_6(), "rule__FunctionDef__RandomizedAssignment_6");
			builder.put(grammarAccess.getFunctionDefAccess().getOwAssignment_7_0(), "rule__FunctionDef__OwAssignment_7_0");
			builder.put(grammarAccess.getFunctionParamAccess().getVariadicAssignment_0(), "rule__FunctionParam__VariadicAssignment_0");
			builder.put(grammarAccess.getFunctionParamAccess().getNameAssignment_1(), "rule__FunctionParam__NameAssignment_1");
			builder.put(grammarAccess.getFunctionParamAccess().getOptAssignment_2(), "rule__FunctionParam__OptAssignment_2");
			builder.put(grammarAccess.getFunctionParamAccess().getTypeAssignment_3_1(), "rule__FunctionParam__TypeAssignment_3_1");
			builder.put(grammarAccess.getFunctionKeyAccess().getElementsAssignment_0(), "rule__FunctionKey__ElementsAssignment_0");
			builder.put(grammarAccess.getFunctionKeyAccess().getElementsAssignment_1_1(), "rule__FunctionKey__ElementsAssignment_1_1");
			builder.put(grammarAccess.getFunctionKeyAccess().getElementsAssignment_1_2_1(), "rule__FunctionKey__ElementsAssignment_1_2_1");
			builder.put(grammarAccess.getFunctionKeyElementAccess().getNameAssignment_0(), "rule__FunctionKeyElement__NameAssignment_0");
			builder.put(grammarAccess.getFunctionKeyElementAccess().getTypeAssignment_1_1(), "rule__FunctionKeyElement__TypeAssignment_1_1");
			builder.put(grammarAccess.getFunctionReturnAccess().getElementsAssignment_0(), "rule__FunctionReturn__ElementsAssignment_0");
			builder.put(grammarAccess.getFunctionReturnAccess().getElementsAssignment_1_1(), "rule__FunctionReturn__ElementsAssignment_1_1");
			builder.put(grammarAccess.getFunctionReturnAccess().getElementsAssignment_1_2_1(), "rule__FunctionReturn__ElementsAssignment_1_2_1");
			builder.put(grammarAccess.getFunctionReturnElementAccess().getNameAssignment_0(), "rule__FunctionReturnElement__NameAssignment_0");
			builder.put(grammarAccess.getFunctionReturnElementAccess().getTypeAssignment_1_1(), "rule__FunctionReturnElement__TypeAssignment_1_1");
			builder.put(grammarAccess.getPropertyDefAccess().getPropertyAssignment_1(), "rule__PropertyDef__PropertyAssignment_1");
			builder.put(grammarAccess.getKnowledgeEqualityDefAccess().getIntroAssignment_0(), "rule__KnowledgeEqualityDef__IntroAssignment_0");
			builder.put(grammarAccess.getKnowledgeEqualityDefAccess().getValueAssignment_1(), "rule__KnowledgeEqualityDef__ValueAssignment_1");
			builder.put(grammarAccess.getKnowledgeEqualityDefAccess().getTargetAssignment_3(), "rule__KnowledgeEqualityDef__TargetAssignment_3");
			builder.put(grammarAccess.getFunctionInversionDefAccess().getInverterAssignment_0(), "rule__FunctionInversionDef__InverterAssignment_0");
			builder.put(grammarAccess.getFunctionInversionDefAccess().getFunctionAssignment_2(), "rule__FunctionInversionDef__FunctionAssignment_2");
			builder.put(grammarAccess.getKnowledgeBaseAccess().getSharedAssignment_0(), "rule__KnowledgeBase__SharedAssignment_0");
			builder.put(grammarAccess.getKnowledgeBaseAccess().getKnowledgeAssignment_2(), "rule__KnowledgeBase__KnowledgeAssignment_2");
			builder.put(grammarAccess.getPrincipalAccess().getNameAssignment_1(), "rule__Principal__NameAssignment_1");
			builder.put(grammarAccess.getPrincipalAccess().getNameAssignment_2_1(), "rule__Principal__NameAssignment_2_1");
			builder.put(grammarAccess.getPrincipalAccess().getKnowledgeAssignment_3_1(), "rule__Principal__KnowledgeAssignment_3_1");
			builder.put(grammarAccess.getKnowledgeDefAccess().getNameAssignment_0_0_0(), "rule__KnowledgeDef__NameAssignment_0_0_0");
			builder.put(grammarAccess.getKnowledgeDefAccess().getValueAssignment_0_2(), "rule__KnowledgeDef__ValueAssignment_0_2");
			builder.put(grammarAccess.getKnowledgeDefAccess().getNameAssignment_1_1_0(), "rule__KnowledgeDef__NameAssignment_1_1_0");
			builder.put(grammarAccess.getKnowledgeDefAccess().getNameAssignment_1_1_1_1(), "rule__KnowledgeDef__NameAssignment_1_1_1_1");
			builder.put(grammarAccess.getKnowledgeDefAccess().getNameAssignment_1_1_1_2_1(), "rule__KnowledgeDef__NameAssignment_1_1_1_2_1");
			builder.put(grammarAccess.getKnowledgeDefSetDestructuringAccess().getAssignmentsAssignment_2_0(), "rule__KnowledgeDefSetDestructuring__AssignmentsAssignment_2_0");
			builder.put(grammarAccess.getKnowledgeDefSetDestructuringAccess().getAssignmentsAssignment_2_1_1(), "rule__KnowledgeDefSetDestructuring__AssignmentsAssignment_2_1_1");
			builder.put(grammarAccess.getKnowledgeDefSetDesctructuringAssignmentAccess().getNameAssignment_0(), "rule__KnowledgeDefSetDesctructuringAssignment__NameAssignment_0");
			builder.put(grammarAccess.getKnowledgeDefSetDesctructuringAssignmentAccess().getFromAssignment_1_1(), "rule__KnowledgeDefSetDesctructuringAssignment__FromAssignment_1_1");
			builder.put(grammarAccess.getKnowledgeDefListDestructuringAccess().getAssignmentsAssignment_2_0(), "rule__KnowledgeDefListDestructuring__AssignmentsAssignment_2_0");
			builder.put(grammarAccess.getKnowledgeDefListDestructuringAccess().getAssignmentsAssignment_2_1_1(), "rule__KnowledgeDefListDestructuring__AssignmentsAssignment_2_1_1");
			builder.put(grammarAccess.getKnowledgeDefListDesctructuringAssignmentAccess().getNameAssignment_2(), "rule__KnowledgeDefListDesctructuringAssignment__NameAssignment_2");
			builder.put(grammarAccess.getKnowledgeListAccess().getValuesAssignment_2_0(), "rule__KnowledgeList__ValuesAssignment_2_0");
			builder.put(grammarAccess.getKnowledgeListAccess().getValuesAssignment_2_1_1(), "rule__KnowledgeList__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getKnowledgeRefAccess().getRefAssignment_0(), "rule__KnowledgeRef__RefAssignment_0");
			builder.put(grammarAccess.getKnowledgeRefAccess().getAccessAssignment_1_1(), "rule__KnowledgeRef__AccessAssignment_1_1");
			builder.put(grammarAccess.getKnowledgeSetAccess().getContentAssignment_2_0(), "rule__KnowledgeSet__ContentAssignment_2_0");
			builder.put(grammarAccess.getKnowledgeSetAccess().getContentAssignment_2_1_1(), "rule__KnowledgeSet__ContentAssignment_2_1_1");
			builder.put(grammarAccess.getKnowledgeSpreadingAccess().getRefAssignment_1(), "rule__KnowledgeSpreading__RefAssignment_1");
			builder.put(grammarAccess.getKnowledgeGeneratorAccess().getTypeAssignment_1(), "rule__KnowledgeGenerator__TypeAssignment_1");
			builder.put(grammarAccess.getKnowledgeFromFunctionAccess().getNameAssignment_0(), "rule__KnowledgeFromFunction__NameAssignment_0");
			builder.put(grammarAccess.getKnowledgeFromFunctionAccess().getArgsAssignment_2(), "rule__KnowledgeFromFunction__ArgsAssignment_2");
			builder.put(grammarAccess.getKnowledgeFromFunctionAccess().getKeyAssignment_4_1(), "rule__KnowledgeFromFunction__KeyAssignment_4_1");
			builder.put(grammarAccess.getKnowledgeFromFunctionArgAccess().getArgsAssignment_0_0(), "rule__KnowledgeFromFunctionArg__ArgsAssignment_0_0");
			builder.put(grammarAccess.getKnowledgeFromFunctionArgAccess().getArgsAssignment_0_1_1(), "rule__KnowledgeFromFunctionArg__ArgsAssignment_0_1_1");
			builder.put(grammarAccess.getCommunicationAccess().getFromAssignment_0(), "rule__Communication__FromAssignment_0");
			builder.put(grammarAccess.getCommunicationAccess().getFromAssignment_1_1(), "rule__Communication__FromAssignment_1_1");
			builder.put(grammarAccess.getCommunicationAccess().getToAssignment_3(), "rule__Communication__ToAssignment_3");
			builder.put(grammarAccess.getCommunicationAccess().getToAssignment_4_1(), "rule__Communication__ToAssignment_4_1");
			builder.put(grammarAccess.getCommunicationAccess().getKnowledgeAssignment_6(), "rule__Communication__KnowledgeAssignment_6");
			builder.put(grammarAccess.getScenarioOptionalAccess().getScenarioAssignment_1(), "rule__ScenarioOptional__ScenarioAssignment_1");
			builder.put(grammarAccess.getScenarioAlternativesAccess().getScenarioAssignment_1_1(), "rule__ScenarioAlternatives__ScenarioAssignment_1_1");
			builder.put(grammarAccess.getScenarioAlternativesAccess().getScenarioAssignment_2_1(), "rule__ScenarioAlternatives__ScenarioAssignment_2_1");
			builder.put(grammarAccess.getScenarioAccess().getNameAssignment_0(), "rule__Scenario__NameAssignment_0");
			builder.put(grammarAccess.getScenarioAccess().getElementsAssignment_2(), "rule__Scenario__ElementsAssignment_2");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getHereAssignment_0(), "rule__KnowledgeCheck__HereAssignment_0");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getOnlyAssignment_1(), "rule__KnowledgeCheck__OnlyAssignment_1");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getTargetAssignment_2_0(), "rule__KnowledgeCheck__TargetAssignment_2_0");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getTargetAssignment_2_1_1(), "rule__KnowledgeCheck__TargetAssignment_2_1_1");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getNotAssignment_3_1(), "rule__KnowledgeCheck__NotAssignment_3_1");
			builder.put(grammarAccess.getKnowledgeCheckAccess().getKnowledgeAssignment_4(), "rule__KnowledgeCheck__KnowledgeAssignment_4");
			builder.put(grammarAccess.getEqualityCheckAccess().getKnowledgeAssignment_0(), "rule__EqualityCheck__KnowledgeAssignment_0");
			builder.put(grammarAccess.getEqualityCheckAccess().getKnowledgeAssignment_1_1(), "rule__EqualityCheck__KnowledgeAssignment_1_1");
			builder.put(grammarAccess.getEqualityCheckAccess().getNotAssignment_3(), "rule__EqualityCheck__NotAssignment_3");
			builder.put(grammarAccess.getFreshnessCheckAccess().getKnowledgeAssignment_0(), "rule__FreshnessCheck__KnowledgeAssignment_0");
			builder.put(grammarAccess.getFreshnessCheckAccess().getKnowledgeAssignment_1_1(), "rule__FreshnessCheck__KnowledgeAssignment_1_1");
			builder.put(grammarAccess.getFreshnessCheckAccess().getNotAssignment_3(), "rule__FreshnessCheck__NotAssignment_3");
			builder.put(grammarAccess.getLinkabilityCheckAccess().getKnowledgeAssignment_0(), "rule__LinkabilityCheck__KnowledgeAssignment_0");
			builder.put(grammarAccess.getLinkabilityCheckAccess().getKnowledgeAssignment_1_1(), "rule__LinkabilityCheck__KnowledgeAssignment_1_1");
			builder.put(grammarAccess.getLinkabilityCheckAccess().getNotAssignment_3(), "rule__LinkabilityCheck__NotAssignment_3");
			builder.put(grammarAccess.getAuthenticationCheckAccess().getPrincipalAssignment_0(), "rule__AuthenticationCheck__PrincipalAssignment_0");
			builder.put(grammarAccess.getAuthenticationCheckAccess().getTargetAssignment_3(), "rule__AuthenticationCheck__TargetAssignment_3");
			builder.put(grammarAccess.getAuthenticationCheckAccess().getKnowledgeAssignment_5(), "rule__AuthenticationCheck__KnowledgeAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private KantGrammarAccess grammarAccess;

	@Override
	protected InternalKantParser createParser() {
		InternalKantParser result = new InternalKantParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public KantGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KantGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
