/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant.impl;

import it.unimi.xtext.kant.FunctionDef;
import it.unimi.xtext.kant.FunctionKey;
import it.unimi.xtext.kant.FunctionParam;
import it.unimi.xtext.kant.FunctionReturn;
import it.unimi.xtext.kant.KantPackage;
import it.unimi.xtext.kant.UniversalIntroduction;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.impl.FunctionDefImpl#getIntro <em>Intro</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.impl.FunctionDefImpl#getName <em>Name</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.impl.FunctionDefImpl#getParams <em>Params</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.impl.FunctionDefImpl#getKey <em>Key</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.impl.FunctionDefImpl#getReturn <em>Return</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.impl.FunctionDefImpl#isRandomized <em>Randomized</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.impl.FunctionDefImpl#isOw <em>Ow</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FunctionDefImpl extends ElementImpl implements FunctionDef
{
  /**
   * The cached value of the '{@link #getIntro() <em>Intro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntro()
   * @generated
   * @ordered
   */
  protected UniversalIntroduction intro;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected EList<String> name;

  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected EList<FunctionParam> params;

  /**
   * The cached value of the '{@link #getKey() <em>Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKey()
   * @generated
   * @ordered
   */
  protected FunctionKey key;

  /**
   * The cached value of the '{@link #getReturn() <em>Return</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturn()
   * @generated
   * @ordered
   */
  protected FunctionReturn return_;

  /**
   * The default value of the '{@link #isRandomized() <em>Randomized</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRandomized()
   * @generated
   * @ordered
   */
  protected static final boolean RANDOMIZED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isRandomized() <em>Randomized</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRandomized()
   * @generated
   * @ordered
   */
  protected boolean randomized = RANDOMIZED_EDEFAULT;

  /**
   * The default value of the '{@link #isOw() <em>Ow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOw()
   * @generated
   * @ordered
   */
  protected static final boolean OW_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOw() <em>Ow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOw()
   * @generated
   * @ordered
   */
  protected boolean ow = OW_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KantPackage.Literals.FUNCTION_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UniversalIntroduction getIntro()
  {
    return intro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIntro(UniversalIntroduction newIntro, NotificationChain msgs)
  {
    UniversalIntroduction oldIntro = intro;
    intro = newIntro;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KantPackage.FUNCTION_DEF__INTRO, oldIntro, newIntro);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIntro(UniversalIntroduction newIntro)
  {
    if (newIntro != intro)
    {
      NotificationChain msgs = null;
      if (intro != null)
        msgs = ((InternalEObject)intro).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KantPackage.FUNCTION_DEF__INTRO, null, msgs);
      if (newIntro != null)
        msgs = ((InternalEObject)newIntro).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KantPackage.FUNCTION_DEF__INTRO, null, msgs);
      msgs = basicSetIntro(newIntro, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KantPackage.FUNCTION_DEF__INTRO, newIntro, newIntro));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getName()
  {
    if (name == null)
    {
      name = new EDataTypeEList<String>(String.class, this, KantPackage.FUNCTION_DEF__NAME);
    }
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FunctionParam> getParams()
  {
    if (params == null)
    {
      params = new EObjectContainmentEList<FunctionParam>(FunctionParam.class, this, KantPackage.FUNCTION_DEF__PARAMS);
    }
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FunctionKey getKey()
  {
    return key;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKey(FunctionKey newKey, NotificationChain msgs)
  {
    FunctionKey oldKey = key;
    key = newKey;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KantPackage.FUNCTION_DEF__KEY, oldKey, newKey);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKey(FunctionKey newKey)
  {
    if (newKey != key)
    {
      NotificationChain msgs = null;
      if (key != null)
        msgs = ((InternalEObject)key).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KantPackage.FUNCTION_DEF__KEY, null, msgs);
      if (newKey != null)
        msgs = ((InternalEObject)newKey).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KantPackage.FUNCTION_DEF__KEY, null, msgs);
      msgs = basicSetKey(newKey, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KantPackage.FUNCTION_DEF__KEY, newKey, newKey));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FunctionReturn getReturn()
  {
    return return_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReturn(FunctionReturn newReturn, NotificationChain msgs)
  {
    FunctionReturn oldReturn = return_;
    return_ = newReturn;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KantPackage.FUNCTION_DEF__RETURN, oldReturn, newReturn);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReturn(FunctionReturn newReturn)
  {
    if (newReturn != return_)
    {
      NotificationChain msgs = null;
      if (return_ != null)
        msgs = ((InternalEObject)return_).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KantPackage.FUNCTION_DEF__RETURN, null, msgs);
      if (newReturn != null)
        msgs = ((InternalEObject)newReturn).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KantPackage.FUNCTION_DEF__RETURN, null, msgs);
      msgs = basicSetReturn(newReturn, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KantPackage.FUNCTION_DEF__RETURN, newReturn, newReturn));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isRandomized()
  {
    return randomized;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRandomized(boolean newRandomized)
  {
    boolean oldRandomized = randomized;
    randomized = newRandomized;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KantPackage.FUNCTION_DEF__RANDOMIZED, oldRandomized, randomized));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isOw()
  {
    return ow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOw(boolean newOw)
  {
    boolean oldOw = ow;
    ow = newOw;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KantPackage.FUNCTION_DEF__OW, oldOw, ow));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case KantPackage.FUNCTION_DEF__INTRO:
        return basicSetIntro(null, msgs);
      case KantPackage.FUNCTION_DEF__PARAMS:
        return ((InternalEList<?>)getParams()).basicRemove(otherEnd, msgs);
      case KantPackage.FUNCTION_DEF__KEY:
        return basicSetKey(null, msgs);
      case KantPackage.FUNCTION_DEF__RETURN:
        return basicSetReturn(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KantPackage.FUNCTION_DEF__INTRO:
        return getIntro();
      case KantPackage.FUNCTION_DEF__NAME:
        return getName();
      case KantPackage.FUNCTION_DEF__PARAMS:
        return getParams();
      case KantPackage.FUNCTION_DEF__KEY:
        return getKey();
      case KantPackage.FUNCTION_DEF__RETURN:
        return getReturn();
      case KantPackage.FUNCTION_DEF__RANDOMIZED:
        return isRandomized();
      case KantPackage.FUNCTION_DEF__OW:
        return isOw();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KantPackage.FUNCTION_DEF__INTRO:
        setIntro((UniversalIntroduction)newValue);
        return;
      case KantPackage.FUNCTION_DEF__NAME:
        getName().clear();
        getName().addAll((Collection<? extends String>)newValue);
        return;
      case KantPackage.FUNCTION_DEF__PARAMS:
        getParams().clear();
        getParams().addAll((Collection<? extends FunctionParam>)newValue);
        return;
      case KantPackage.FUNCTION_DEF__KEY:
        setKey((FunctionKey)newValue);
        return;
      case KantPackage.FUNCTION_DEF__RETURN:
        setReturn((FunctionReturn)newValue);
        return;
      case KantPackage.FUNCTION_DEF__RANDOMIZED:
        setRandomized((Boolean)newValue);
        return;
      case KantPackage.FUNCTION_DEF__OW:
        setOw((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KantPackage.FUNCTION_DEF__INTRO:
        setIntro((UniversalIntroduction)null);
        return;
      case KantPackage.FUNCTION_DEF__NAME:
        getName().clear();
        return;
      case KantPackage.FUNCTION_DEF__PARAMS:
        getParams().clear();
        return;
      case KantPackage.FUNCTION_DEF__KEY:
        setKey((FunctionKey)null);
        return;
      case KantPackage.FUNCTION_DEF__RETURN:
        setReturn((FunctionReturn)null);
        return;
      case KantPackage.FUNCTION_DEF__RANDOMIZED:
        setRandomized(RANDOMIZED_EDEFAULT);
        return;
      case KantPackage.FUNCTION_DEF__OW:
        setOw(OW_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KantPackage.FUNCTION_DEF__INTRO:
        return intro != null;
      case KantPackage.FUNCTION_DEF__NAME:
        return name != null && !name.isEmpty();
      case KantPackage.FUNCTION_DEF__PARAMS:
        return params != null && !params.isEmpty();
      case KantPackage.FUNCTION_DEF__KEY:
        return key != null;
      case KantPackage.FUNCTION_DEF__RETURN:
        return return_ != null;
      case KantPackage.FUNCTION_DEF__RANDOMIZED:
        return randomized != RANDOMIZED_EDEFAULT;
      case KantPackage.FUNCTION_DEF__OW:
        return ow != OW_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", randomized: ");
    result.append(randomized);
    result.append(", ow: ");
    result.append(ow);
    result.append(')');
    return result.toString();
  }

} //FunctionDefImpl
