/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant.impl;

import it.unimi.xtext.kant.KantPackage;
import it.unimi.xtext.kant.KnowledgeEqualityDef;
import it.unimi.xtext.kant.KnowledgeValue;
import it.unimi.xtext.kant.UniversalIntroduction;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Knowledge Equality Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.impl.KnowledgeEqualityDefImpl#getIntro <em>Intro</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.impl.KnowledgeEqualityDefImpl#getValue <em>Value</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.impl.KnowledgeEqualityDefImpl#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @generated
 */
public class KnowledgeEqualityDefImpl extends MinimalEObjectImpl.Container implements KnowledgeEqualityDef
{
  /**
   * The cached value of the '{@link #getIntro() <em>Intro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntro()
   * @generated
   * @ordered
   */
  protected UniversalIntroduction intro;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected KnowledgeValue value;

  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected KnowledgeValue target;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected KnowledgeEqualityDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KantPackage.Literals.KNOWLEDGE_EQUALITY_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UniversalIntroduction getIntro()
  {
    return intro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIntro(UniversalIntroduction newIntro, NotificationChain msgs)
  {
    UniversalIntroduction oldIntro = intro;
    intro = newIntro;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO, oldIntro, newIntro);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIntro(UniversalIntroduction newIntro)
  {
    if (newIntro != intro)
    {
      NotificationChain msgs = null;
      if (intro != null)
        msgs = ((InternalEObject)intro).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO, null, msgs);
      if (newIntro != null)
        msgs = ((InternalEObject)newIntro).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO, null, msgs);
      msgs = basicSetIntro(newIntro, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO, newIntro, newIntro));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KnowledgeValue getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue(KnowledgeValue newValue, NotificationChain msgs)
  {
    KnowledgeValue oldValue = value;
    value = newValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE, oldValue, newValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValue(KnowledgeValue newValue)
  {
    if (newValue != value)
    {
      NotificationChain msgs = null;
      if (value != null)
        msgs = ((InternalEObject)value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE, null, msgs);
      if (newValue != null)
        msgs = ((InternalEObject)newValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE, null, msgs);
      msgs = basicSetValue(newValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE, newValue, newValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KnowledgeValue getTarget()
  {
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTarget(KnowledgeValue newTarget, NotificationChain msgs)
  {
    KnowledgeValue oldTarget = target;
    target = newTarget;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET, oldTarget, newTarget);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTarget(KnowledgeValue newTarget)
  {
    if (newTarget != target)
    {
      NotificationChain msgs = null;
      if (target != null)
        msgs = ((InternalEObject)target).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET, null, msgs);
      if (newTarget != null)
        msgs = ((InternalEObject)newTarget).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET, null, msgs);
      msgs = basicSetTarget(newTarget, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET, newTarget, newTarget));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO:
        return basicSetIntro(null, msgs);
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE:
        return basicSetValue(null, msgs);
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET:
        return basicSetTarget(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO:
        return getIntro();
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE:
        return getValue();
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET:
        return getTarget();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO:
        setIntro((UniversalIntroduction)newValue);
        return;
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE:
        setValue((KnowledgeValue)newValue);
        return;
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET:
        setTarget((KnowledgeValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO:
        setIntro((UniversalIntroduction)null);
        return;
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE:
        setValue((KnowledgeValue)null);
        return;
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET:
        setTarget((KnowledgeValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__INTRO:
        return intro != null;
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__VALUE:
        return value != null;
      case KantPackage.KNOWLEDGE_EQUALITY_DEF__TARGET:
        return target != null;
    }
    return super.eIsSet(featureID);
  }

} //KnowledgeEqualityDefImpl
