/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant.impl;

import it.unimi.xtext.kant.KantPackage;
import it.unimi.xtext.kant.KnowledgeDefDestructuring;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Knowledge Def Destructuring</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class KnowledgeDefDestructuringImpl extends KnowledgeDefImpl implements KnowledgeDefDestructuring
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected KnowledgeDefDestructuringImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KantPackage.Literals.KNOWLEDGE_DEF_DESTRUCTURING;
  }

} //KnowledgeDefDestructuringImpl
