/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant.impl;

import it.unimi.xtext.kant.KantPackage;
import it.unimi.xtext.kant.ScenarioAlternatives;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Scenario Alternatives</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ScenarioAlternativesImpl extends ScenarioBranchingImpl implements ScenarioAlternatives
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScenarioAlternativesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KantPackage.Literals.SCENARIO_ALTERNATIVES;
  }

} //ScenarioAlternativesImpl
