/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant.impl;

import it.unimi.xtext.kant.KantPackage;
import it.unimi.xtext.kant.ScenarioOptional;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Scenario Optional</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ScenarioOptionalImpl extends ScenarioBranchingImpl implements ScenarioOptional
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScenarioOptionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KantPackage.Literals.SCENARIO_OPTIONAL;
  }

} //ScenarioOptionalImpl
