/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Authentication Check</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.AuthenticationCheck#getPrincipal <em>Principal</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.AuthenticationCheck#getTarget <em>Target</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.AuthenticationCheck#getKnowledge <em>Knowledge</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getAuthenticationCheck()
 * @model
 * @generated
 */
public interface AuthenticationCheck extends Check
{
  /**
   * Returns the value of the '<em><b>Principal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Principal</em>' attribute.
   * @see #setPrincipal(String)
   * @see it.unimi.xtext.kant.KantPackage#getAuthenticationCheck_Principal()
   * @model
   * @generated
   */
  String getPrincipal();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.AuthenticationCheck#getPrincipal <em>Principal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Principal</em>' attribute.
   * @see #getPrincipal()
   * @generated
   */
  void setPrincipal(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see it.unimi.xtext.kant.KantPackage#getAuthenticationCheck_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.AuthenticationCheck#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Knowledge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledge</em>' containment reference.
   * @see #setKnowledge(KnowledgeValue)
   * @see it.unimi.xtext.kant.KantPackage#getAuthenticationCheck_Knowledge()
   * @model containment="true"
   * @generated
   */
  KnowledgeValue getKnowledge();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.AuthenticationCheck#getKnowledge <em>Knowledge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Knowledge</em>' containment reference.
   * @see #getKnowledge()
   * @generated
   */
  void setKnowledge(KnowledgeValue value);

} // AuthenticationCheck
