/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unimi.xtext.kant.KantPackage#getCheck()
 * @model
 * @generated
 */
public interface Check extends Element
{
} // Check
