/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Communication</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.Communication#getFrom <em>From</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.Communication#getTo <em>To</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.Communication#getKnowledge <em>Knowledge</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getCommunication()
 * @model
 * @generated
 */
public interface Communication extends Element
{
  /**
   * Returns the value of the '<em><b>From</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' attribute list.
   * @see it.unimi.xtext.kant.KantPackage#getCommunication_From()
   * @model unique="false"
   * @generated
   */
  EList<String> getFrom();

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute list.
   * @see it.unimi.xtext.kant.KantPackage#getCommunication_To()
   * @model unique="false"
   * @generated
   */
  EList<String> getTo();

  /**
   * Returns the value of the '<em><b>Knowledge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledge</em>' containment reference.
   * @see #setKnowledge(Knowledge)
   * @see it.unimi.xtext.kant.KantPackage#getCommunication_Knowledge()
   * @model containment="true"
   * @generated
   */
  Knowledge getKnowledge();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.Communication#getKnowledge <em>Knowledge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Knowledge</em>' containment reference.
   * @see #getKnowledge()
   * @generated
   */
  void setKnowledge(Knowledge value);

} // Communication
