/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Return Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.FunctionReturnElement#getName <em>Name</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionReturnElement#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getFunctionReturnElement()
 * @model
 * @generated
 */
public interface FunctionReturnElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute list.
   * @see it.unimi.xtext.kant.KantPackage#getFunctionReturnElement_Name()
   * @model unique="false"
   * @generated
   */
  EList<String> getName();

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(KnowledgeValue)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionReturnElement_Type()
   * @model containment="true"
   * @generated
   */
  KnowledgeValue getType();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionReturnElement#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(KnowledgeValue value);

} // FunctionReturnElement
