/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Inversion Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.FunctionInversionDef#getInverter <em>Inverter</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionInversionDef#getFunction <em>Function</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getFunctionInversionDef()
 * @model
 * @generated
 */
public interface FunctionInversionDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Inverter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inverter</em>' attribute.
   * @see #setInverter(String)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionInversionDef_Inverter()
   * @model
   * @generated
   */
  String getInverter();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionInversionDef#getInverter <em>Inverter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inverter</em>' attribute.
   * @see #getInverter()
   * @generated
   */
  void setInverter(String value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see #setFunction(String)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionInversionDef_Function()
   * @model
   * @generated
   */
  String getFunction();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionInversionDef#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see #getFunction()
   * @generated
   */
  void setFunction(String value);

} // FunctionInversionDef
