/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.FunctionParam#isVariadic <em>Variadic</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionParam#getName <em>Name</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionParam#isOpt <em>Opt</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionParam#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getFunctionParam()
 * @model
 * @generated
 */
public interface FunctionParam extends EObject
{
  /**
   * Returns the value of the '<em><b>Variadic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variadic</em>' attribute.
   * @see #setVariadic(boolean)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionParam_Variadic()
   * @model
   * @generated
   */
  boolean isVariadic();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionParam#isVariadic <em>Variadic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variadic</em>' attribute.
   * @see #isVariadic()
   * @generated
   */
  void setVariadic(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionParam_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionParam#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Opt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opt</em>' attribute.
   * @see #setOpt(boolean)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionParam_Opt()
   * @model
   * @generated
   */
  boolean isOpt();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionParam#isOpt <em>Opt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opt</em>' attribute.
   * @see #isOpt()
   * @generated
   */
  void setOpt(boolean value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(KnowledgeValue)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionParam_Type()
   * @model containment="true"
   * @generated
   */
  KnowledgeValue getType();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionParam#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(KnowledgeValue value);

} // FunctionParam
