/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.FunctionDef#getIntro <em>Intro</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionDef#getName <em>Name</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionDef#getParams <em>Params</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionDef#getKey <em>Key</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionDef#getReturn <em>Return</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionDef#isRandomized <em>Randomized</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.FunctionDef#isOw <em>Ow</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getFunctionDef()
 * @model
 * @generated
 */
public interface FunctionDef extends Element
{
  /**
   * Returns the value of the '<em><b>Intro</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intro</em>' containment reference.
   * @see #setIntro(UniversalIntroduction)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionDef_Intro()
   * @model containment="true"
   * @generated
   */
  UniversalIntroduction getIntro();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionDef#getIntro <em>Intro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Intro</em>' containment reference.
   * @see #getIntro()
   * @generated
   */
  void setIntro(UniversalIntroduction value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute list.
   * @see it.unimi.xtext.kant.KantPackage#getFunctionDef_Name()
   * @model unique="false"
   * @generated
   */
  EList<String> getName();

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link it.unimi.xtext.kant.FunctionParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see it.unimi.xtext.kant.KantPackage#getFunctionDef_Params()
   * @model containment="true"
   * @generated
   */
  EList<FunctionParam> getParams();

  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference.
   * @see #setKey(FunctionKey)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionDef_Key()
   * @model containment="true"
   * @generated
   */
  FunctionKey getKey();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionDef#getKey <em>Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' containment reference.
   * @see #getKey()
   * @generated
   */
  void setKey(FunctionKey value);

  /**
   * Returns the value of the '<em><b>Return</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return</em>' containment reference.
   * @see #setReturn(FunctionReturn)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionDef_Return()
   * @model containment="true"
   * @generated
   */
  FunctionReturn getReturn();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionDef#getReturn <em>Return</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return</em>' containment reference.
   * @see #getReturn()
   * @generated
   */
  void setReturn(FunctionReturn value);

  /**
   * Returns the value of the '<em><b>Randomized</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Randomized</em>' attribute.
   * @see #setRandomized(boolean)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionDef_Randomized()
   * @model
   * @generated
   */
  boolean isRandomized();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionDef#isRandomized <em>Randomized</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Randomized</em>' attribute.
   * @see #isRandomized()
   * @generated
   */
  void setRandomized(boolean value);

  /**
   * Returns the value of the '<em><b>Ow</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ow</em>' attribute.
   * @see #setOw(boolean)
   * @see it.unimi.xtext.kant.KantPackage#getFunctionDef_Ow()
   * @model
   * @generated
   */
  boolean isOw();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.FunctionDef#isOw <em>Ow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ow</em>' attribute.
   * @see #isOw()
   * @generated
   */
  void setOw(boolean value);

} // FunctionDef
