/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.FunctionKey#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getFunctionKey()
 * @model
 * @generated
 */
public interface FunctionKey extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link it.unimi.xtext.kant.FunctionKeyElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see it.unimi.xtext.kant.KantPackage#getFunctionKey_Elements()
   * @model containment="true"
   * @generated
   */
  EList<FunctionKeyElement> getElements();

} // FunctionKey
