/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see it.unimi.xtext.kant.KantPackage
 * @generated
 */
public interface KantFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  KantFactory eINSTANCE = it.unimi.xtext.kant.impl.KantFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Protocol</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Protocol</em>'.
   * @generated
   */
  Protocol createProtocol();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Universal Introduction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Universal Introduction</em>'.
   * @generated
   */
  UniversalIntroduction createUniversalIntroduction();

  /**
   * Returns a new object of class '<em>Function Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Def</em>'.
   * @generated
   */
  FunctionDef createFunctionDef();

  /**
   * Returns a new object of class '<em>Function Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Param</em>'.
   * @generated
   */
  FunctionParam createFunctionParam();

  /**
   * Returns a new object of class '<em>Function Key</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Key</em>'.
   * @generated
   */
  FunctionKey createFunctionKey();

  /**
   * Returns a new object of class '<em>Function Key Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Key Element</em>'.
   * @generated
   */
  FunctionKeyElement createFunctionKeyElement();

  /**
   * Returns a new object of class '<em>Function Return</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Return</em>'.
   * @generated
   */
  FunctionReturn createFunctionReturn();

  /**
   * Returns a new object of class '<em>Function Return Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Return Element</em>'.
   * @generated
   */
  FunctionReturnElement createFunctionReturnElement();

  /**
   * Returns a new object of class '<em>Property Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property Def</em>'.
   * @generated
   */
  PropertyDef createPropertyDef();

  /**
   * Returns a new object of class '<em>Knowledge Equality Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Equality Def</em>'.
   * @generated
   */
  KnowledgeEqualityDef createKnowledgeEqualityDef();

  /**
   * Returns a new object of class '<em>Function Inversion Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Inversion Def</em>'.
   * @generated
   */
  FunctionInversionDef createFunctionInversionDef();

  /**
   * Returns a new object of class '<em>Knowledge Base</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Base</em>'.
   * @generated
   */
  KnowledgeBase createKnowledgeBase();

  /**
   * Returns a new object of class '<em>Principal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Principal</em>'.
   * @generated
   */
  Principal createPrincipal();

  /**
   * Returns a new object of class '<em>Knowledge</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge</em>'.
   * @generated
   */
  Knowledge createKnowledge();

  /**
   * Returns a new object of class '<em>Knowledge Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Def</em>'.
   * @generated
   */
  KnowledgeDef createKnowledgeDef();

  /**
   * Returns a new object of class '<em>Knowledge Def Destructuring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Def Destructuring</em>'.
   * @generated
   */
  KnowledgeDefDestructuring createKnowledgeDefDestructuring();

  /**
   * Returns a new object of class '<em>Knowledge Def Set Destructuring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Def Set Destructuring</em>'.
   * @generated
   */
  KnowledgeDefSetDestructuring createKnowledgeDefSetDestructuring();

  /**
   * Returns a new object of class '<em>Knowledge Def Set Desctructuring Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Def Set Desctructuring Assignment</em>'.
   * @generated
   */
  KnowledgeDefSetDesctructuringAssignment createKnowledgeDefSetDesctructuringAssignment();

  /**
   * Returns a new object of class '<em>Knowledge Def List Destructuring</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Def List Destructuring</em>'.
   * @generated
   */
  KnowledgeDefListDestructuring createKnowledgeDefListDestructuring();

  /**
   * Returns a new object of class '<em>Knowledge Def List Desctructuring Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Def List Desctructuring Assignment</em>'.
   * @generated
   */
  KnowledgeDefListDesctructuringAssignment createKnowledgeDefListDesctructuringAssignment();

  /**
   * Returns a new object of class '<em>Knowledge Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Value</em>'.
   * @generated
   */
  KnowledgeValue createKnowledgeValue();

  /**
   * Returns a new object of class '<em>Knowledge List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge List</em>'.
   * @generated
   */
  KnowledgeList createKnowledgeList();

  /**
   * Returns a new object of class '<em>Knowledge Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Ref</em>'.
   * @generated
   */
  KnowledgeRef createKnowledgeRef();

  /**
   * Returns a new object of class '<em>Knowledge Set</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Set</em>'.
   * @generated
   */
  KnowledgeSet createKnowledgeSet();

  /**
   * Returns a new object of class '<em>Knowledge Spreading</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Spreading</em>'.
   * @generated
   */
  KnowledgeSpreading createKnowledgeSpreading();

  /**
   * Returns a new object of class '<em>Knowledge Generator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Generator</em>'.
   * @generated
   */
  KnowledgeGenerator createKnowledgeGenerator();

  /**
   * Returns a new object of class '<em>Knowledge From Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge From Function</em>'.
   * @generated
   */
  KnowledgeFromFunction createKnowledgeFromFunction();

  /**
   * Returns a new object of class '<em>Knowledge From Function Arg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge From Function Arg</em>'.
   * @generated
   */
  KnowledgeFromFunctionArg createKnowledgeFromFunctionArg();

  /**
   * Returns a new object of class '<em>Communication</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Communication</em>'.
   * @generated
   */
  Communication createCommunication();

  /**
   * Returns a new object of class '<em>Scenario Branching</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scenario Branching</em>'.
   * @generated
   */
  ScenarioBranching createScenarioBranching();

  /**
   * Returns a new object of class '<em>Scenario Optional</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scenario Optional</em>'.
   * @generated
   */
  ScenarioOptional createScenarioOptional();

  /**
   * Returns a new object of class '<em>Scenario Alternatives</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scenario Alternatives</em>'.
   * @generated
   */
  ScenarioAlternatives createScenarioAlternatives();

  /**
   * Returns a new object of class '<em>Scenario</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scenario</em>'.
   * @generated
   */
  Scenario createScenario();

  /**
   * Returns a new object of class '<em>Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Check</em>'.
   * @generated
   */
  Check createCheck();

  /**
   * Returns a new object of class '<em>Knowledge Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Knowledge Check</em>'.
   * @generated
   */
  KnowledgeCheck createKnowledgeCheck();

  /**
   * Returns a new object of class '<em>Equality Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equality Check</em>'.
   * @generated
   */
  EqualityCheck createEqualityCheck();

  /**
   * Returns a new object of class '<em>Freshness Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Freshness Check</em>'.
   * @generated
   */
  FreshnessCheck createFreshnessCheck();

  /**
   * Returns a new object of class '<em>Linkability Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Linkability Check</em>'.
   * @generated
   */
  LinkabilityCheck createLinkabilityCheck();

  /**
   * Returns a new object of class '<em>Authentication Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Authentication Check</em>'.
   * @generated
   */
  AuthenticationCheck createAuthenticationCheck();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  KantPackage getKantPackage();

} //KantFactory
