/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Base</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeBase#isShared <em>Shared</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeBase#getKnowledge <em>Knowledge</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeBase()
 * @model
 * @generated
 */
public interface KnowledgeBase extends Element
{
  /**
   * Returns the value of the '<em><b>Shared</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shared</em>' attribute.
   * @see #setShared(boolean)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeBase_Shared()
   * @model
   * @generated
   */
  boolean isShared();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeBase#isShared <em>Shared</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shared</em>' attribute.
   * @see #isShared()
   * @generated
   */
  void setShared(boolean value);

  /**
   * Returns the value of the '<em><b>Knowledge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledge</em>' containment reference.
   * @see #setKnowledge(Knowledge)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeBase_Knowledge()
   * @model containment="true"
   * @generated
   */
  Knowledge getKnowledge();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeBase#getKnowledge <em>Knowledge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Knowledge</em>' containment reference.
   * @see #getKnowledge()
   * @generated
   */
  void setKnowledge(Knowledge value);

} // KnowledgeBase
