/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeRef#getRef <em>Ref</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeRef#getAccess <em>Access</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeRef()
 * @model
 * @generated
 */
public interface KnowledgeRef extends KnowledgeValue
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' attribute.
   * @see #setRef(String)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeRef_Ref()
   * @model
   * @generated
   */
  String getRef();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeRef#getRef <em>Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' attribute.
   * @see #getRef()
   * @generated
   */
  void setRef(String value);

  /**
   * Returns the value of the '<em><b>Access</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Access</em>' attribute list.
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeRef_Access()
   * @model unique="false"
   * @generated
   */
  EList<String> getAccess();

} // KnowledgeRef
