/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeValue()
 * @model
 * @generated
 */
public interface KnowledgeValue extends Knowledge
{
} // KnowledgeValue
