/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledge()
 * @model
 * @generated
 */
public interface Knowledge extends EObject
{
} // Knowledge
