/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Equality Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeEqualityDef#getIntro <em>Intro</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeEqualityDef#getValue <em>Value</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeEqualityDef#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeEqualityDef()
 * @model
 * @generated
 */
public interface KnowledgeEqualityDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Intro</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intro</em>' containment reference.
   * @see #setIntro(UniversalIntroduction)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeEqualityDef_Intro()
   * @model containment="true"
   * @generated
   */
  UniversalIntroduction getIntro();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeEqualityDef#getIntro <em>Intro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Intro</em>' containment reference.
   * @see #getIntro()
   * @generated
   */
  void setIntro(UniversalIntroduction value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(KnowledgeValue)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeEqualityDef_Value()
   * @model containment="true"
   * @generated
   */
  KnowledgeValue getValue();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeEqualityDef#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(KnowledgeValue value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(KnowledgeValue)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeEqualityDef_Target()
   * @model containment="true"
   * @generated
   */
  KnowledgeValue getTarget();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeEqualityDef#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(KnowledgeValue value);

} // KnowledgeEqualityDef
