/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Def Destructuring</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeDefDestructuring()
 * @model
 * @generated
 */
public interface KnowledgeDefDestructuring extends KnowledgeDef
{
} // KnowledgeDefDestructuring
