/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge From Function Arg</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeFromFunctionArg#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeFromFunctionArg()
 * @model
 * @generated
 */
public interface KnowledgeFromFunctionArg extends EObject
{
  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link it.unimi.xtext.kant.KnowledgeValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeFromFunctionArg_Args()
   * @model containment="true"
   * @generated
   */
  EList<KnowledgeValue> getArgs();

} // KnowledgeFromFunctionArg
