/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeDef#getName <em>Name</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeDef#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeDef()
 * @model
 * @generated
 */
public interface KnowledgeDef extends Knowledge
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute list.
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeDef_Name()
   * @model unique="false"
   * @generated
   */
  EList<String> getName();

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(KnowledgeValue)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeDef_Value()
   * @model containment="true"
   * @generated
   */
  KnowledgeValue getValue();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeDef#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(KnowledgeValue value);

} // KnowledgeDef
