/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Spreading</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeSpreading#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeSpreading()
 * @model
 * @generated
 */
public interface KnowledgeSpreading extends KnowledgeFromFunctionArg
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference.
   * @see #setRef(KnowledgeValue)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeSpreading_Ref()
   * @model containment="true"
   * @generated
   */
  KnowledgeValue getRef();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeSpreading#getRef <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' containment reference.
   * @see #getRef()
   * @generated
   */
  void setRef(KnowledgeValue value);

} // KnowledgeSpreading
