/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Def Set Destructuring</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeDefSetDestructuring#getAssignments <em>Assignments</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeDefSetDestructuring()
 * @model
 * @generated
 */
public interface KnowledgeDefSetDestructuring extends KnowledgeDefDestructuring
{
  /**
   * Returns the value of the '<em><b>Assignments</b></em>' containment reference list.
   * The list contents are of type {@link it.unimi.xtext.kant.KnowledgeDefSetDesctructuringAssignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignments</em>' containment reference list.
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeDefSetDestructuring_Assignments()
   * @model containment="true"
   * @generated
   */
  EList<KnowledgeDefSetDesctructuringAssignment> getAssignments();

} // KnowledgeDefSetDestructuring
