/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge Generator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeGenerator#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeGenerator()
 * @model
 * @generated
 */
public interface KnowledgeGenerator extends KnowledgeValue
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeGenerator_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeGenerator#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

} // KnowledgeGenerator
