/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge From Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeFromFunction#getName <em>Name</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeFromFunction#getArgs <em>Args</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.KnowledgeFromFunction#getKey <em>Key</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getKnowledgeFromFunction()
 * @model
 * @generated
 */
public interface KnowledgeFromFunction extends KnowledgeValue
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeFromFunction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeFromFunction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(KnowledgeFromFunctionArg)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeFromFunction_Args()
   * @model containment="true"
   * @generated
   */
  KnowledgeFromFunctionArg getArgs();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeFromFunction#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(KnowledgeFromFunctionArg value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference.
   * @see #setKey(KnowledgeValue)
   * @see it.unimi.xtext.kant.KantPackage#getKnowledgeFromFunction_Key()
   * @model containment="true"
   * @generated
   */
  KnowledgeValue getKey();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.KnowledgeFromFunction#getKey <em>Key</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' containment reference.
   * @see #getKey()
   * @generated
   */
  void setKey(KnowledgeValue value);

} // KnowledgeFromFunction
