/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Principal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.Principal#getName <em>Name</em>}</li>
 *   <li>{@link it.unimi.xtext.kant.Principal#getKnowledge <em>Knowledge</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getPrincipal()
 * @model
 * @generated
 */
public interface Principal extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute list.
   * @see it.unimi.xtext.kant.KantPackage#getPrincipal_Name()
   * @model unique="false"
   * @generated
   */
  EList<String> getName();

  /**
   * Returns the value of the '<em><b>Knowledge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledge</em>' containment reference.
   * @see #setKnowledge(Knowledge)
   * @see it.unimi.xtext.kant.KantPackage#getPrincipal_Knowledge()
   * @model containment="true"
   * @generated
   */
  Knowledge getKnowledge();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.Principal#getKnowledge <em>Knowledge</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Knowledge</em>' containment reference.
   * @see #getKnowledge()
   * @generated
   */
  void setKnowledge(Knowledge value);

} // Principal
