/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.PropertyDef#getProperty <em>Property</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getPropertyDef()
 * @model
 * @generated
 */
public interface PropertyDef extends Element
{
  /**
   * Returns the value of the '<em><b>Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' containment reference.
   * @see #setProperty(EObject)
   * @see it.unimi.xtext.kant.KantPackage#getPropertyDef_Property()
   * @model containment="true"
   * @generated
   */
  EObject getProperty();

  /**
   * Sets the value of the '{@link it.unimi.xtext.kant.PropertyDef#getProperty <em>Property</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' containment reference.
   * @see #getProperty()
   * @generated
   */
  void setProperty(EObject value);

} // PropertyDef
