/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Alternatives</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unimi.xtext.kant.KantPackage#getScenarioAlternatives()
 * @model
 * @generated
 */
public interface ScenarioAlternatives extends ScenarioBranching
{
} // ScenarioAlternatives
