/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Optional</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unimi.xtext.kant.KantPackage#getScenarioOptional()
 * @model
 * @generated
 */
public interface ScenarioOptional extends ScenarioBranching
{
} // ScenarioOptional
