/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Branching</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.ScenarioBranching#getScenario <em>Scenario</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getScenarioBranching()
 * @model
 * @generated
 */
public interface ScenarioBranching extends Element
{
  /**
   * Returns the value of the '<em><b>Scenario</b></em>' containment reference list.
   * The list contents are of type {@link it.unimi.xtext.kant.Scenario}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenario</em>' containment reference list.
   * @see it.unimi.xtext.kant.KantPackage#getScenarioBranching_Scenario()
   * @model containment="true"
   * @generated
   */
  EList<Scenario> getScenario();

} // ScenarioBranching
