/**
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.kant;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Universal Introduction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unimi.xtext.kant.UniversalIntroduction#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see it.unimi.xtext.kant.KantPackage#getUniversalIntroduction()
 * @model
 * @generated
 */
public interface UniversalIntroduction extends EObject
{
  /**
   * Returns the value of the '<em><b>Args</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' attribute list.
   * @see it.unimi.xtext.kant.KantPackage#getUniversalIntroduction_Args()
   * @model unique="false"
   * @generated
   */
  EList<String> getArgs();

} // UniversalIntroduction
