/*
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.serializer;

import com.google.inject.Inject;
import it.unimi.xtext.services.KantGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class KantSyntacticSequencer extends AbstractSyntacticSequencer {

	protected KantGrammarAccess grammarAccess;
	protected AbstractElementAlias match_KnowledgeDefListDesctructuringAssignment_FullStopFullStopFullStopKeyword_0_1_or__Keyword_1_1;
	protected AbstractElementAlias match_KnowledgeDef_ConstKeyword_1_0_0_or_FreshKeyword_1_0_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (KantGrammarAccess) access;
		match_KnowledgeDefListDesctructuringAssignment_FullStopFullStopFullStopKeyword_0_1_or__Keyword_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getKnowledgeDefListDesctructuringAssignmentAccess().getFullStopFullStopFullStopKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getKnowledgeDefListDesctructuringAssignmentAccess().get_Keyword_1_1()));
		match_KnowledgeDef_ConstKeyword_1_0_0_or_FreshKeyword_1_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getKnowledgeDefAccess().getConstKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getKnowledgeDefAccess().getFreshKeyword_1_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_KnowledgeDefListDesctructuringAssignment_FullStopFullStopFullStopKeyword_0_1_or__Keyword_1_1.equals(syntax))
				emit_KnowledgeDefListDesctructuringAssignment_FullStopFullStopFullStopKeyword_0_1_or__Keyword_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_KnowledgeDef_ConstKeyword_1_0_0_or_FreshKeyword_1_0_1.equals(syntax))
				emit_KnowledgeDef_ConstKeyword_1_0_0_or_FreshKeyword_1_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '...' | '_'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_KnowledgeDefListDesctructuringAssignment_FullStopFullStopFullStopKeyword_0_1_or__Keyword_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'const' | 'fresh'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '{' name+=ID
	 *     (rule start) (ambiguity) name+=ID
	 
	 * </pre>
	 */
	protected void emit_KnowledgeDef_ConstKeyword_1_0_0_or_FreshKeyword_1_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
