/*
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKantScopeProvider extends DelegatingScopeProvider {
}
