/*
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class KantStandaloneSetup extends KantStandaloneSetupGenerated {

	public static void doSetup() {
		new KantStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
