/*
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.ui;

import com.google.inject.Injector;
import it.unimi.xtext.kant.ui.internal.KantActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KantExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(KantActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		KantActivator activator = KantActivator.getInstance();
		return activator != null ? activator.getInjector(KantActivator.IT_UNIMI_XTEXT_KANT) : null;
	}

}
