/*
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.ui.tests;

import com.google.inject.Injector;
import it.unimi.xtext.kant.ui.internal.KantActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class KantUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return KantActivator.getInstance().getInjector("it.unimi.xtext.Kant");
	}

}
