/*
 * generated by Xtext 2.29.0
 */
package it.unimi.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class KantUiModule extends AbstractKantUiModule {

	public KantUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
