name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: "0"

      - name: Check if main contains this tag
        run: "git branch -a --contains ${GITHUB_REF#refs/tags/} | grep \"remotes\\/origin\\/main\" -E -m 1 || exit 1"

      - name: Check root package and tag versions
        run: "grep \"\\\"version\\\": \\\"${GITHUB_REF#refs/tags/v}\\\"\" package.json -m 1 || exit 1"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Run generation
        run: pnpm run generate

      - name: Run check
        run: pnpm run check

      # TO-DO package publishing

      # main repo release

      - name: Generate docs for release
        run: pnpm run docs

      - name: Zip docs for release
        run: 'cd docs/out && zip -r "../../kant_docs_${GITHUB_REF#refs/tags/}.zip" .'

      - name: Package extension for release
        run: "pnpm run package:extension"

      - name: Release
        uses: softprops/action-gh-release@v0.1.13
        with:
          files: |
            kant_docs_*.zip
            packages/extension/*.vsix
          fail_on_unmatched_files: true
          body: "All notable changes should be readable in repo at [`CHANGELOG.md`](CHANGELOG.md) or consulting the attached documentation."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
